name: Robot Framework Tests - Python

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  Robot_Framework_Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.1
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get update
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb

      - name: Verify Google Chrome Installation
        run: |
          google-chrome --version
          chromedriver --version

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install webdriver-manager
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install selenium  # Ensure selenium is installed

      - name: Install Client Dependencies
        run: |
          cd client
          npm install

#      - name: Install Server Dependencies
#        run: |
#          cd server
#          npm install

#      - name: Start Server
#        run: |
#          cd server
#          npm start
#          echo "Server started"

      - name: Start Client
        run: |
          cd client
          npm start &
          echo "Client started"

      - name: Install wait-on
        run: |
          npm install -g wait-on

      - name: Wait for client to Be Ready
        run: |
          echo "Waiting for client to be ready..."
          sleep 10

      - name: Verify Chromium Installation
        run: |
          chromium-browser --version
          chromedriver --version

      - name: Run Robot Framework Tests
        run: |
          cd client/robot
          robot .

      - name: Test Report Generation
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Report                # Name of the artifact
          path: output                 # Path to Robot Framework output (default is 'output' directory)